{% set name = "stdlibs" %}
{% set version = "2023.12.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stdlibs-{{ version }}.tar.gz
  sha256: c2041f2a133773e234205d72f48980aebbecec47b17206dd9679747581ae8372

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3,<4
  run:
    - python >=3.7

test:
  imports:
    - stdlibs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://stdlibs.omnilib.dev
  summary: List of packages in the stdlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
