{% set name = "stdlibs" %}
{% set version = "2025.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stdlibs-{{ version }}.tar.gz
  sha256: bb327c1369434c453ef68f3d0ac37d707f568e498f19d7a88f483843b99338e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - stdlibs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://stdlibs.omnilib.dev
  summary: List of packages in the stdlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
