{% set name = "stdlibs" %}
{% set version = "2025.5.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stdlibs-{{ version }}.tar.gz
  sha256: 75d55a0b7b070ec44bd7dae5bc1ee1a6cea742122fb4253313cb4ab354f7f0c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - stdlibs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://stdlibs.omnilib.dev
  summary: List of packages in the stdlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
