{% set name = "stdlibs" %}
{% set version = "2026.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/stdlibs-{{ version }}.tar.gz
  sha256: 0da5ac692879757df75fd944ebabfae11b2d6454a2643658699a1c0a1f4bb91a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - stdlibs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://stdlibs.omnilib.dev
  summary: List of packages in the stdlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
